# Generated by Django 3.2.5 on 2021-07-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permissionrule',
            name='rule',
            field=models.JSONField(),
        ),
    ]
